// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBkQUyM476DKN6s7hhUJNYC5MB2zbYu8',
    appId: '1:701950421308:web:49c868e195a5eb50ff9639',
    messagingSenderId: '701950421308',
    projectId: 'travel-community-2e4fb',
    authDomain: 'travel-community-2e4fb.firebaseapp.com',
    databaseURL: 'https://travel-community-2e4fb-default-rtdb.firebaseio.com',
    storageBucket: 'travel-community-2e4fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1a5hMfeLgCne7jZQO8CwnIyjxVHwa7XQ',
    appId: '1:701950421308:android:65690fc21ad7e887ff9639',
    messagingSenderId: '701950421308',
    projectId: 'travel-community-2e4fb',
    databaseURL: 'https://travel-community-2e4fb-default-rtdb.firebaseio.com',
    storageBucket: 'travel-community-2e4fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT5KHVJ8DQ55HdqvuEDvzoPNZSRd8SDzs',
    appId: '1:701950421308:ios:dd64138bc7a5357dff9639',
    messagingSenderId: '701950421308',
    projectId: 'travel-community-2e4fb',
    databaseURL: 'https://travel-community-2e4fb-default-rtdb.firebaseio.com',
    storageBucket: 'travel-community-2e4fb.appspot.com',
    androidClientId: '701950421308-ieivvnrimt7ubkq31ulm2fn2s663c2v8.apps.googleusercontent.com',
    iosClientId: '701950421308-bjsjjkb4rj01l3lcerkkvte3b7clba88.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT5KHVJ8DQ55HdqvuEDvzoPNZSRd8SDzs',
    appId: '1:701950421308:ios:dd64138bc7a5357dff9639',
    messagingSenderId: '701950421308',
    projectId: 'travel-community-2e4fb',
    databaseURL: 'https://travel-community-2e4fb-default-rtdb.firebaseio.com',
    storageBucket: 'travel-community-2e4fb.appspot.com',
    androidClientId: '701950421308-ieivvnrimt7ubkq31ulm2fn2s663c2v8.apps.googleusercontent.com',
    iosClientId: '701950421308-bjsjjkb4rj01l3lcerkkvte3b7clba88.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcBkQUyM476DKN6s7hhUJNYC5MB2zbYu8',
    appId: '1:701950421308:web:c3fa28724d2fdafdff9639',
    messagingSenderId: '701950421308',
    projectId: 'travel-community-2e4fb',
    authDomain: 'travel-community-2e4fb.firebaseapp.com',
    databaseURL: 'https://travel-community-2e4fb-default-rtdb.firebaseio.com',
    storageBucket: 'travel-community-2e4fb.appspot.com',
  );
}
